# https://nikitabobko.github.io/AeroSpace/guide#configuring-aerospace

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    cmd-alt-space = 'mode service'

    cmd-alt-enter = 'fullscreen'

    cmd-alt-h = 'focus left'
    cmd-alt-j = 'focus down'
    cmd-alt-k = 'focus up'
    cmd-alt-l = 'focus right'

    cmd-alt-shift-h = 'move left'
    cmd-alt-shift-j = 'move down'
    cmd-alt-shift-k = 'move up'
    cmd-alt-shift-l = 'move right'

    cmd-alt-left  = 'exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace prev'
    cmd-alt-right = 'exec-and-forget aerospace list-workspaces --monitor focused --empty no | aerospace workspace next'

    cmd-alt-m = 'move-workspace-to-monitor --wrap-around next'

    cmd-alt-period = 'layout tiles horizontal vertical'
    cmd-alt-slash = 'layout accordion horizontal vertical'

[mode.service.binding]
    esc = ['reload-config', 'mode main']

    a = ['workspace 1', 'mode main']
    s = ['workspace 2', 'mode main']
    d = ['workspace 3', 'mode main']
    f = ['workspace 4', 'mode main']
    z = ['workspace 5', 'mode main']
    x = ['workspace 6', 'mode main']
    c = ['workspace 7', 'mode main']
    v = ['workspace 8', 'mode main']

    shift-a = ['move-node-to-workspace 1', 'mode main']
    shift-s = ['move-node-to-workspace 2', 'mode main']
    shift-d = ['move-node-to-workspace 3', 'mode main']
    shift-f = ['move-node-to-workspace 4', 'mode main']
    shift-z = ['move-node-to-workspace 5', 'mode main']
    shift-x = ['move-node-to-workspace 6', 'mode main']
    shift-c = ['move-node-to-workspace 7', 'mode main']
    shift-v = ['move-node-to-workspace 8', 'mode main']

    h = ['join-with left', 'mode main']
    j = ['join-with down', 'mode main']
    k = ['join-with up', 'mode main']
    l = ['join-with right', 'mode main']

[[on-window-detected]]
    if.app-id = 'us.zoom.xos'
    if.window-title-regex-substring = 'Zoom Meeting'
    run = 'move-node-to-workspace z'

[[on-window-detected]]
    if.app-name-regex-substring = 'System Settings|Finder|Steam|zoom.us'
    run = 'layout floating'
    check-further-callbacks = true
