cask "wezterm"
cask "maccy"
cask "notunes"
cask "nikitabobko/tap/aerospace"

brew "colordiff"
brew "corepack"
brew "dlvhdr/formulae/diffnav"
brew "fd"
brew "fzf"
brew "git-delta"
brew "grip"
brew "jq"
brew "less"
brew "ruff"
brew "starship"
brew "tree"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Snowflake
brew "vault"
brew "grpcurl"
