#!/usr/bin/env zsh

set -eux -o pipefail

cd "$(dirname "${0:A}")"

mkdir -p man/man1

bin/git-branch-manager --help > man/man1/git-branch-manager.1
bin/git-branch-manager-make-branch --help > man/man1/git-branch-manager-make-branch.1
