#!/bin/bash

cd "$(dirname ${BASH_SOURCE[0]})"

FILES=(
    'bash.d'
    'bash_profile'
    'vimrc'
)

for FILE in "${FILES[@]}"; do
    DEST="$HOME/.$FILE"
    if [[ ! -h $DEST ]]; then
        ln -sf "$PWD/$FILE" "$DEST"
    fi
done
