#!/bin/bash

alias chrome="open -a 'Google Chrome'"
alias grep="grep --color"
alias ll="ls -lhAt"

function sublime() {
    if [[ $# == 0 ]]; then
        open -a 'Sublime Text' .
    else
        open -a 'Sublime Text' "$@"
    fi
}

alias subl="sublime"
alias desk="cd ~/Desktop"
