#!/bin/bash

alias chrome="open -a 'Google Chrome'"

function subl() {
    if [[ $# == 0 ]]; then
        open -a 'Sublime Text' .
    else
        open -a 'Sublime Text' "$@"
    fi
}

alias grep="grep --color"
alias ll="ls -lhAt"
alias desk="cd ~/Desktop"
alias nv='nvim'

# touch a file, creating the directory if it doesn't already exist
function touch() {
    for f in "$@"; do
        mkdir -p "$(dirname "$f")"
        command touch "$f"
    done
}
