#!/bin/bash

# get the current directory, replacing $HOME with ~ and adding
# a slash to the end, if necessary
function get_curr_dir() {
    local curr_dir=${PWD/$HOME/"~"}
    if [[ $curr_dir != */ ]]; then
        curr_dir="$curr_dir/"
    fi
    echo $curr_dir
}

# cd into the git root
function root() {
    cd "$(git rev-parse --show-toplevel)"
}

# rename the given file
function rn() {
    local old=${1?}
    local new=${2?}
    mv "${old}" "$(dirname "${old}")/${new}"
}

# change the extension of the given file
function chext() {
    local old=${1?}
    local ext=${2?}
    if [[ "${ext}" != .* ]]; then
        ext=".${ext}"
    fi

    mv "${old}" "${old%\.*}${ext}"
}
