#!/bin/bash

# git tab completion
source /usr/local/bin/git-completion.bash

# exit non-zero if not a git repo
function is_repo() {
    git rev-parse HEAD &> /dev/null
}

# exit non-zero if not a git worktree
function is_worktree() {
    if is_repo; then
        (root && [[ $(git rev-parse --git-dir) != ".git" ]])
    else
        return 1
    fi
}

# get the name of the current repo; works in worktrees
function get_repo() {
    GIT_URL=$(git remote -v | grep origin | head -n 1 | awk '{ print $2 }')
    basename "$(sed 's|\.git$||' <<< "$GIT_URL")"
}
