#!/bin/bash

# git tab completion
source /usr/local/bin/git-completion.bash

# exit non-zero if not a git repo
function is_repo() {
    git rev-parse HEAD > /dev/null 2>&1
}

# exit non-zero if not a git worktree
function is_worktree() {
    if is_repo; then
        (root && [[ $(git rev-parse --git-dir) != ".git" ]])
    else
        return 1
    fi
}

# get the name of the current repo; works in worktrees
function get_repo() {
    basename "$(git rev-parse --absolute-git-dir | sed 's|/\.git.*||')"
}

# get the current branch, or the commit hash if not on a branch
function get_branch() {
    local label=$(git rev-parse --abbrev-ref HEAD)
    if [[ $label == "HEAD" ]]; then
        git rev-parse --short=8 HEAD
    else
        echo $label
    fi
}
