#!/bin/bash

# get the git prompt
function get_vc_prompt() {
    if is_repo; then
        local repo=$(get_repo)
        local label=$(git rev-parse --abbrev-ref HEAD)
        if [[ $label == "HEAD" ]]; then
            label=$(git rev-parse --short=8 HEAD)
        fi
        echo "($repo:$label)"
    fi
}

# convert the given exit code into an indicator
function display_code() {
    case $1 in
        0) echo $(emojify :ok_hand:) ;;
        1) echo $(emojify :exclamation:) ;;
        *) echo "${RED}$(emojify :exclamation:)($1)" ;;
    esac
}

# any actions to run before prompting for commands
function pre_prompt() {
    # needs to be first
    display_code $?

    # print title every time
    update_title

    local curr_date="[$(date +"%F %T")]"
    local curr_dir="$(get_curr_dir)"
    local vc_prompt="$(get_vc_prompt)"
    local one_line="$curr_date $curr_dir $vc_prompt"

    printf "\n${POWDER_BLUE}%s " "$curr_date"
    if [[ ${#one_line} -gt $COLUMNS ]]; then
        printf "${MAGENTA}%s\n${GREEN}%s" "$vc_prompt" "$curr_dir"
    else
        printf "${GREEN}%s ${MAGENTA}%s" "$curr_dir" "$vc_prompt"
    fi
    printf "${NORMAL}\n"
}

function get_prompt() {
    echo "$(emojify :zap:) "
}
