#!/bin/bash

OK_HAND="\xF0\x9F\x91\x8C"
EXCLAMATION="\xE2\x9D\x97\x20"
ZAP="\xE2\x9A\xA1\x0A"

# get the git prompt
function get_vc_prompt() {
    if is_repo; then
        local repo=$(get_repo)
        local label=$(get_branch)
        echo "($repo:$label)"
    fi
}

# convert the recent exit code into an indicator
function display_code() {
    local code=$?
    case $code in
        0) echo -e $OK_HAND ;;
        1) echo -e $EXCLAMATION ;;
        *) echo -e "${EXCLAMATION} ${RED}($code)${NORMAL}" ;;
    esac
}

# any actions to run before prompting for commands
function pre_prompt() {
    # needs to be first
    display_code

    # print title every time
    update_title

    local curr_date="[$(date +"%F %T")]"
    local curr_dir="$(get_curr_dir)"
    local vc_prompt="$(get_vc_prompt)"
    local one_line="$curr_date $curr_dir $vc_prompt"

    printf "\n${POWDER_BLUE}%s " "$curr_date"
    if [[ ${#one_line} -gt $COLUMNS ]]; then
        printf "${MAGENTA}%s\n${GREEN}%s" "$vc_prompt" "$curr_dir"
    else
        printf "${GREEN}%s ${MAGENTA}%s" "$curr_dir" "$vc_prompt"
    fi
    printf "${NORMAL}\n"
}
