#!/bin/bash

# set SSH_AUTH_SOCK
function set_agent_sock() {
    local sock_folder
    for sock_folder in $(ls $TMPDIR | grep '^ssh-.*'); do
        local sock=$(find $TMPDIR/$sock_folder -name "agent.*")
        if [[ ! -z $sock ]]; then
            if SSH_AUTH_SOCK=$sock ssh-add -l > /dev/null 2>&1; then
                echo "Setting SSH_AUTH_SOCK to: $sock"
                export SSH_AUTH_SOCK=$sock
                return 0
            else
                # delete old sock file
                rm -rf $sock
            fi
        fi
    done
    echo "No ssh-agent sock file found."
    return 1
}

function start_ssh_agent() {
    eval "$(ssh-agent -s)"
    local SSH_KEYS=(
        id_rsa
    )
    (cd ~/.ssh && ssh-add "${SSH_KEYS[@]}")
}

# Check if ssh-agent is running. If an ssh-agent is already running,
# set SSH_AUTH_SOCK
function check_ssh_agent() {
    export SSH_AGENT_PID=$(pgrep -f 'ssh-agent -s')

    if [[ -z $SSH_AGENT_PID ]]; then
        echo 'No SSH agent running. Run `start_ssh_agent`.'
    else
        set_agent_sock
    fi
}
