#!/bin/bash

# track current title
: ${CUSTOM_TITLE:=""}

# helper to set title
function title() {
    CUSTOM_TITLE="$*"
}

# update title in terminal
function update_title() {
    local title=$CUSTOM_TITLE
    if [[ -z $title ]]; then
        if is_repo; then
            title="$(get_repo):$(get_branch)"
        else
            title=$(get_curr_dir)
        fi
    fi

    printf "\e]0;%s\7" "$title"
}
