#!/bin/bash

# track current title
: ${CUSTOM_TITLE:=""}

# helper to set title
function title() {
    CUSTOM_TITLE="$*"
}

# update title in terminal
function update_title() {
    local title=$CUSTOM_TITLE
    if [[ -z $title ]]; then
        title=$(get_curr_dir)
    fi

    printf "\e]0;%s\7" "$title"
}
